steps:
# build the container image
- name: "docker"
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/flask-app', '.']
# push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push","asia.gcr.io/$PROJECT_ID/flask-app"]
# deploy container to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=asia.gcr.io/$PROJECT_ID/flask-app
  - --region=asia-east1
  - --location=autopilot-secret-cluster
  - --namespace=gcp-devops
