apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: flask-app
        image: asia.gcr.io/long-micron-397706/flask-app
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
