apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: "gcp-devops"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      serviceAccountName: readonly-sa
      containers:
      - name: flask-app
        image: asia.gcr.io/long-micron-397706/flask-app
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
                  resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-service"
  namespace: "gcp-devops"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp"
  type: "LoadBalancer"
